services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
        - postgresdata:/var/lib/postgresql/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

volumes:
  postgresdata:
  redisdata:
